changelog:
  exclude:
    authors:
      - pre-commit-ci
      - dependabot[bot]
      - github-actions
      - Copilot
  categories:
    - title: New Features 💫
      labels:
        - enhancement
    - title: Bug Fixes 🐞
      labels:
        - bug
    - title: Maintenance 🛠️
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"
