import logging


class CodeGenerator:
    def __init__(self, controller, node_sequence):
        self.ct = controller
        self.node_sequence = node_sequence

        self.code = self.generate_code()

    @staticmethod
    def tab(num_tabs=1, tab_size=4):
        """Return a string of tabs for indentation."""
        return " " * (num_tabs * tab_size)

    def _indent(self, code, num_tabs=1):
        """Indent a code string by a given number of tabs."""
        indent_str = self.tab(num_tabs)
        # If line empty, don't indent
        indented_code = "\n".join(
            indent_str + line for line in code.splitlines() if line != ""
        )
        indented_code += "\n"
        return indented_code

    def _build_header(self, functions):
        code = (
            "# This code was generated by mne-nodes\n\n"
            "import os\n"
            "import traceback\n"
            "import logging\n"
            "from tqdm import tqdm\n"
            "from rich.pretty import pprint\n"
            "import mne\n"
            "from mne_bids import BIDSPath, read_raw_bids, get_datatypes, get_bids_path_from_fname\n"
            "import mne_nodes\n"
            "from mne_nodes.pipeline.controller import Controller\n"
            "# Activate matplotlibs interactive mode\n"
            "import matplotlib.pyplot as plt\n"
            "plt.ion()\n"
            "# Disable gui-mode\n"
            "mne_nodes.gui_mode = False\n\n"
            "# Load controller\n"
            f"ct = Controller(config_path='{self.ct.ensure_config_path(interactive=False).as_posix()}')\n\n"
            "# Inject modules into global namespace\n"
            "globals().update(ct.modules)\n"
            "# Import modules\n"
        )
        # Add module imports
        modules = set(functions.values())
        for module in modules:
            if module == "mne_functions":
                code += "import mne\n"
            else:
                code += f"from {module} import {', '.join([f for f, m in functions.items() if m == module])}\n"

        return code

    def generate_code(self):
        """Convert a list of instructions to a Python code string."""
        # start code with header and imports
        functions = {
            n["name"]: self.ct.get_function_meta(n["name"])["module"]
            for n in self.node_sequence
            if n["class"] == "FunctionNode"
        }
        code = self._build_header(functions)
        code += "\n# Execute pipeline\n"
        # Get available datatypes
        data_types = self.ct.get_datatypes()
        # Ordering targets (files first)
        targets = {t: [] for t in ["file", "group"]}
        for n in self.node_sequence:
            if n["class"] == "FunctionNode":
                func_meta = self.ct.get_function_meta(n["name"])
                target = func_meta["target"]
                if target not in targets:
                    logging.warning(
                        f"Target '{target}' not recognized. Step {n['name']} will be ignored in code generation."
                    )
                    continue
                targets[target].append(n)
        # Iterate nodes
        for target, nodes in targets.items():
            if len(nodes) == 0:
                continue
            code += f"# Target: {target}\n"
            for selection_type in [
                key
                for key, items in self.ct.get("selected_inputs").items()
                if len(items) > 0
            ]:
                if (selection_type in self.ct.scopes and target == "file") or (
                    selection_type in data_types and target == "group"
                ):
                    continue
                loaded_data = []
                code += f"# Selection-Type: {selection_type}\n"
                if target == "group":
                    code += f"group = ct.get_group_by('{selection_type}')\n"
                code += f"for item in ct.get('selected_inputs')['{selection_type}']:\n"
                # Prepare bids-paths
                if target == "file" and selection_type in data_types:
                    code += self._indent("bp = get_bids_path_from_fname(item)\n", 1)
                else:
                    # For group-data, load and return generators of the group-members
                    code += self._indent("members = group[item]\n", 1)
                for n in nodes:
                    name = n["name"]
                    func_meta = self.ct.get_function_meta(name)
                    if target == "file":
                        inputs = [i for i in n["inputs"] if i not in loaded_data]
                    else:
                        # For group-data generators need to be reloaded since they exhaust on every use
                        inputs = n["inputs"]
                    for ip in inputs:
                        # Load selected data-types (if not already loaded)
                        if ip == "raw":
                            # Load raw from original bids-dataset
                            if target == "file":
                                code += self._indent(
                                    "bp_raw = bp.copy().update(root=ct.bids_root)\n", 1
                                )
                                code += self._indent("raw = read_raw_bids(bp_raw)\n", 1)
                            else:
                                code += self._indent(
                                    "raw = (read_raw_bids(rp) for rp in members)\n", 1
                                )
                            loaded_data.append("raw")
                        elif ip == "info":
                            if "raw" in loaded_data:
                                if target == "file":
                                    code += self._indent("info = raw.info\n", 1)
                                else:
                                    code += self._indent(
                                        "info = (r.info for r in raw)\n", 1
                                    )
                            else:
                                if target == "file":
                                    code += self._indent(
                                        "bp_info = bp.copy().update(root=ct.bids_root)\n",
                                        1,
                                    )
                                    code += self._indent(
                                        "info = mne.io.read_info(bp_info.fpath)\n", 1
                                    )
                                else:
                                    code += self._indent(
                                        "info = (mne.io.read_info(bp.copy().update(root=ct.bids_root).fpath) for bp in members)\n",
                                        1,
                                    )
                            loaded_data.append("info")
                        elif ip == "subject":
                            # Load (freesurfer) subject if available
                            code += self._indent(
                                "subject = ct.check_subject(bp.subject)\n", 1
                            )
                            code += self._indent("if subject is None:\n", 1)
                            code += self._indent("continue", 2)
                            loaded_data.append("subject")
                        else:
                            # Load data from derivatives
                            input_meta = self.ct.get_input_meta(
                                function_name=name, input_name=ip
                            )
                            load_func = input_meta.get("load", None)
                            if load_func is not None:
                                suffix = input_meta.get("suffix") or ip
                                # Load data from storage
                                code += self._indent(f"# Load {ip}", 1)
                                code += self._indent(
                                    f"load_kwargs = ct.get_input_meta('{name}', '{ip}').get('load_kwargs', {{}})\n",
                                    1,
                                )
                                if target == "file":
                                    code += self._indent(
                                        f"data_path = bp.copy().update(suffix='{suffix}', root=ct.deriv_root, check=False).fpath\n",
                                        1,
                                    )
                                    # This assumes, that the file-path is always the first argument in a load-function
                                    code += self._indent(
                                        f"{ip} = {load_func}(data_path, **load_kwargs)\n",
                                        1,
                                    )
                                else:
                                    code += self._indent(
                                        f"{ip} = ({load_func}(dp, **load_kwargs) for dp in [bp.copy().update(suffix='{suffix}', root=ct.deriv_root, check=False).fpath for bp in members])\n",
                                        1,
                                    )
                            loaded_data.append(ip)
                    code += self._indent(f"# Execute function {name}\n", 1)
                    code += self._indent(
                        f"print(f'Executing {name} for {{item}} with the following parameters:')\n",
                        1,
                    )
                    code += self._indent(
                        f"func_params = ct.func_parameters('{name}')", 1
                    )
                    code += self._indent("pprint(func_params)\n", 1)
                    outputs = ", ".join([op for op in n["outputs"]])
                    loaded_data += n["outputs"]
                    inputs = ", ".join([f"{ip}={ip}" for ip in n["inputs"]])
                    func_line = ""
                    if len(outputs) > 0:
                        func_line += f"{outputs} = "
                    if "mne" in func_meta["module"]:
                        func_name = f"{func_meta['module']}.{name}"
                    else:
                        func_name = name
                    func_line += f"{func_name}("
                    if len(inputs) > 0:
                        func_line += f"{inputs}, **func_params)"
                    else:
                        func_line += "**func_params)"
                    code += self._indent(func_line, 1)
                    # Save outputs (if enabled)
                    if n["checked"]:
                        for op in n["outputs"]:
                            output_meta = self.ct.get_output_meta(
                                function_name=name, output_name=op
                            )
                            save_func = output_meta.get("save", None)
                            if save_func is not None:
                                suffix = output_meta.get("suffix") or op
                                # Save data to storage
                                code += self._indent(f"# Save {op}\n", 1)
                                if target == "file":
                                    code += self._indent(
                                        f"data_path = bp.copy().update(suffix='{suffix}', root=ct.deriv_root, check=False).fpath\n",
                                        1,
                                    )
                                else:
                                    code += self._indent(
                                        f"data_path = members[0].copy().update(subject=item, suffix='{suffix}', root=ct.deriv_root, check=False)\n"
                                        "data_path.mkdir(exist_ok=True)\n",
                                        1,
                                    )
                                code += self._indent(
                                    f"save_kwargs = ct.get_output_meta(function_name='{name}', output_name='{op}').get('save_kwargs', {{}})\n",
                                    1,
                                )
                                if save_func.startswith("."):
                                    code += self._indent(
                                        f"{op}{save_func}(data_path, **save_kwargs)\n",
                                        1,
                                    )
                                else:
                                    # This assumes, that the file-path is always the first argument in a save-function
                                    code += self._indent(
                                        f"{save_func}(data_path, {op}, **save_kwargs)\n",
                                        1,
                                    )

        code += "# Keep matplotlib plots open\nplt.ioff()\nplt.show(block=True)\n"

        return code
