import re
from collections import defaultdict

from mne_nodes.logger import logger


class CodeGenerator:
    def __init__(self, controller, node_sequence):
        self.ct = controller
        self.node_sequence = node_sequence

        self.code = self.generate_code()

    @staticmethod
    def tab(num_tabs=1, tab_size=4):
        """Return a string of tabs for indentation."""
        return " " * (num_tabs * tab_size)

    @staticmethod
    def base_func_name(name):
        """Strip the disambiguating '-<N>' node-name suffix, e.g. for duplicate
        function nodes, to get the actual importable/callable function name."""
        return re.sub(r"-\d+$", "", name)

    def _indent(self, code, num_tabs=1):
        """Indent a code string by a given number of tabs."""
        indent_str = self.tab(num_tabs)
        # If line empty, don't indent
        indented_code = "\n".join(
            indent_str + line for line in code.splitlines() if line != ""
        )
        indented_code += "\n"
        return indented_code

    def _build_header(self, function_names, extra_modules=()):
        code = (
            "# This code was generated by mne-nodes\n\n"
            "import mne_nodes\n"
            "from mne_bids import get_bids_path_from_fname\n"
            "from mne_nodes.pipeline.controller import Controller\n"
            "# Disable gui-mode\n"
            "mne_nodes.gui_mode = False\n\n"
            "# Load controller\n"
            f"ct = Controller(config_path='{self.ct.ensure_config_path(interactive=False).as_posix()}')\n\n"
            "# Inject plugins into global namespace\n"
            "globals().update(ct.plugins)\n"
            "# Import plugins\n"
        )
        # Add plugin imports
        plugins_functions = defaultdict(list)
        seen_base_names = set()
        for function_name in function_names:
            base_name = self.base_func_name(function_name)
            if base_name in seen_base_names:
                continue
            seen_base_names.add(base_name)
            plugin_name = self.ct.get_plugin_from_function(function_name)
            plugins_functions[plugin_name].append(base_name)
        for plugin_name, functions in plugins_functions.items():
            if plugin_name == "mne_functions":
                module_functions_sorted = defaultdict(list)
                for func in functions:
                    module_name = self.ct.get_function_meta(func).get(
                        "module_name", None
                    )
                    if module_name is not None:
                        module_functions_sorted[module_name].append(func)
                for module, funcs in module_functions_sorted.items():
                    code += f"from {module} import {', '.join(funcs)}\n"
            else:
                code += f"from {plugin_name} import {', '.join(functions)}\n"

        # Import modules needed for reading/writing derivatives directly
        # (their functions are referenced module-qualified, not imported by name).
        for module in sorted(extra_modules):
            code += f"import {module}\n"

        return code

    def _qualified_call(self, func_name, required_modules):
        """Return a module-qualified call expression for a registered function.

        Records the function's module in ``required_modules`` so it can be
        imported in the header, unless the function is a class method (in
        which case it must be called on an instance instead).
        """
        func_meta = self.ct.get_function_meta(func_name)
        module_name = func_meta.get("module_name")
        if module_name:
            required_modules.add(module_name)
            return f"{module_name}.{func_name}"
        return func_name

    def generate_code(self):
        """Convert a list of instructions to a Python code string."""
        # Get available datatypes
        data_types = self.ct.get_datatypes()
        # Ordering targets (files first)
        targets = {t: [] for t in ["file", "group"]}
        import_function_names = []
        # A node fed (even indirectly) by a group-scoped upstream node must
        # also run in group scope, regardless of its own function's target.
        node_target_by_name = {}
        for n in self.node_sequence:
            if n["class"] == "FunctionNode":
                func_meta = self.ct.get_function_meta(n["name"])
                # Only import functions that are not methods of classes
                class_name = func_meta["class_name"]
                if class_name is None:
                    import_function_names.append(n["name"])
                upstream_targets = {
                    node_target_by_name[cn]
                    for connected in n["inputs"].values()
                    for cn in connected
                    if cn in node_target_by_name
                }
                target = "group" if "group" in upstream_targets else func_meta["target"]
                node_target_by_name[n["name"]] = target
                if target not in targets:
                    logger.warning(
                        f"Target '{target}' not recognized. Step {n['name']} will be ignored in code generation."
                    )
                    continue
                targets[target].append(n)
        # Modules needed for module-qualified read/write function calls,
        # collected while building the body and imported in the header.
        required_modules = set()
        body = ""
        # Iterate nodes
        for target, nodes in targets.items():
            if len(nodes) == 0:
                continue
            body += f"# Target: {target}\n"
            for selection_type in [
                key
                for key, items in self.ct.get("selected_inputs").items()
                if len(items) > 0
            ]:
                if (selection_type in self.ct.scopes and target == "file") or (
                    selection_type in data_types and target == "group"
                ):
                    continue
                loaded_data = set()
                body += f"# Selection-Type: {selection_type}\n"
                if target == "group":
                    body += f"group = ct.get_group_by('{selection_type}')\n"
                body += f"for item in ct.get('selected_inputs')['{selection_type}']:\n"
                # Prepare bids-paths
                if target == "file" and selection_type in data_types:
                    body += self._indent("bp = get_bids_path_from_fname(item)\n", 1)
                else:
                    # For group-data, load and return generators of the group-members
                    body += self._indent("members = group[item]\n", 1)
                for n in nodes:
                    name = n["name"]
                    func_meta = self.ct.get_function_meta(name)
                    # Check which inputs are already satisfied (incl. via accepted_ports)
                    # before deciding what still needs to be loaded from disk.
                    func_inputs, loading_needed = self.ct.func_inputs(name, loaded_data)
                    # Only load inputs that are actually connected to something.
                    # Unconnected (optional) inputs are simply omitted from the call.
                    # A connected-but-unloaded input means the pipeline is being
                    # started from a subsequent node, so it must be read from disk.
                    if target == "file":
                        inputs = [ip for ip in loading_needed if n["inputs"].get(ip)]
                    else:
                        # For group-data generators need to be reloaded since they exhaust on every use
                        inputs = [
                            ip for ip, connected in n["inputs"].items() if connected
                        ]
                    # Bids-path(s) to pass to the controller loading-methods
                    source = "bp" if target == "file" else "members"
                    for ip in inputs:
                        # Load selected data-types (if not already loaded)
                        if ip == "raw":
                            body += self._indent(
                                f"raw, event_id = ct.load_raw({source})\n", 1
                            )
                            loaded_data.update({"raw", "event_id"})
                        elif ip == "info":
                            raw_arg = "raw" if "raw" in loaded_data else "None"
                            body += self._indent(
                                f"info = ct.load_info({source}, raw={raw_arg})\n", 1
                            )
                            loaded_data.add("info")
                        elif ip == "subject":
                            # Load (freesurfer) subject if available
                            subject_source = "bp" if target == "file" else "members[0]"
                            body += self._indent(
                                f"subject = ct.load_subject({subject_source}.subject)\n",
                                1,
                            )
                            body += self._indent("if not subject:\n", 1)
                            body += self._indent("continue", 2)
                            loaded_data.add("subject")
                        else:
                            # Load data from derivatives; prefer this input's own
                            # read meta, else fall back to another function's read
                            # meta for a name it accepts (e.g. "evoked" for an
                            # input that merely accepts it via accepted_ports).
                            input_meta = self.ct.get_input_meta(
                                function_name=name, input_name=ip
                            )
                            load_name = ip
                            own_read = input_meta.get("read") is not None
                            if not own_read:
                                for alias in input_meta.get("accepted_ports") or []:
                                    alias_meta = self.ct.get_load_meta_for_port(alias)
                                    if alias_meta is not None:
                                        input_meta = alias_meta
                                        load_name = alias
                                        break
                            read_func = input_meta.get("read", None)
                            if read_func is not None:
                                suffix = input_meta.get("suffix") or load_name
                                read_call = self._qualified_call(
                                    read_func, required_modules
                                )
                                # Load data from storage
                                body += self._indent(f"# Load {load_name}", 1)
                                # Read function's own parameters serve as its kwargs.
                                body += self._indent(
                                    f"read_kwargs = {{k: v for k, v in ct.func_parameters('{read_func}').items() if k != 'fname'}}\n",
                                    1,
                                )
                                if target == "file":
                                    body += self._indent(
                                        f"data_path = bp.copy().update(suffix='{suffix}', root=ct.deriv_root, check=False).fpath\n",
                                        1,
                                    )
                                    # This assumes, that the file-path is always the first argument in a load-function
                                    body += self._indent(
                                        f"{load_name} = {read_call}(data_path, **read_kwargs)\n",
                                        1,
                                    )
                                else:
                                    body += self._indent(
                                        f"{load_name} = ({read_call}(dp, **read_kwargs) for dp in [bp.copy().update(suffix='{suffix}', root=ct.deriv_root, check=False).fpath for bp in members])\n",
                                        1,
                                    )
                                loaded_data.add(load_name)
                                func_inputs[ip] = load_name
                        # A loaded port's variable is named after itself.
                        if ip in loaded_data:
                            func_inputs[ip] = ip
                    body += self._indent(f"# Execute function {name}\n", 1)
                    body += self._indent(
                        f"print(f'Executing {name} for {{item}} with the following parameters:')\n",
                        1,
                    )
                    outputs = ", ".join([op for op in n["outputs"]])
                    func_line = ""
                    if len(outputs) > 0:
                        func_line += f"{outputs} = "
                    # Inject (lowercase) class-name if the function is a method of a class
                    # This assumes, that instance references of a class always have the same name as the class but lowercase
                    base_name = self.base_func_name(name)
                    if func_meta["class_name"] is not None:
                        lower_class = func_meta["class_name"].lower()
                        func_line += f"{lower_class}."
                        func_name = base_name.split(".")[-1]
                        func_inputs.pop(lower_class, None)
                    else:
                        func_name = base_name
                    func_line += f"{func_name}("
                    if len(func_inputs) > 0:
                        inputs = ", ".join(
                            f"{param}={var}" for param, var in func_inputs.items()
                        )
                        func_line += f"{inputs}, **ct.func_parameters('{name}'))"
                    else:
                        func_line += f"**ct.func_parameters('{name}'))"
                    body += self._indent(func_line, 1)
                    # Save outputs (if enabled)
                    if n["checked"]:
                        for op in n["outputs"]:
                            output_meta = self.ct.get_output_meta(
                                function_name=name, output_name=op
                            )
                            write_func = output_meta.get("write", None)
                            if write_func is not None:
                                suffix = output_meta.get("suffix") or op
                                # Save data to storage
                                body += self._indent(f"# Save {op}\n", 1)
                                if target == "file":
                                    body += self._indent(
                                        f"data_path = bp.copy().update(suffix='{suffix}', root=ct.deriv_root, check=False).fpath\n",
                                        1,
                                    )
                                else:
                                    body += self._indent(
                                        f"data_path = members[0].copy().update(subject=item, suffix='{suffix}', root=ct.deriv_root, check=False)\n"
                                        "data_path.mkdir(exist_ok=True)\n",
                                        1,
                                    )
                                # Write function's own parameters serve as its kwargs.
                                body += self._indent(
                                    f"write_kwargs = {{k: v for k, v in ct.func_parameters('{write_func}').items() if k != 'fname'}}\n",
                                    1,
                                )
                                write_func_meta = self.ct.get_function_meta(write_func)
                                if write_func_meta["class_name"] is not None:
                                    # Called on the produced instance directly.
                                    method_name = write_func.split(".")[-1]
                                    body += self._indent(
                                        f"{op}.{method_name}(data_path, **write_kwargs)\n",
                                        1,
                                    )
                                else:
                                    write_call = self._qualified_call(
                                        write_func, required_modules
                                    )
                                    # This assumes, that the file-path is always the first argument in a save-function
                                    body += self._indent(
                                        f"{write_call}(data_path, {op}, **write_kwargs)\n",
                                        1,
                                    )
                    loaded_data.update(n["outputs"])

        # Create import header, including modules for read/write functions used above.
        header = self._build_header(import_function_names, required_modules)

        return header + body
